[package]
name = "rad1o-rust"
version = "0.1.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
rad1o = { version = "0.0.0", path = "rad1o" }

[profile.release]
lto = true
panic = 'abort'

[target.thumbv7em-none-eabihf.dependencies]

[[bin]]
name = "logo"
path = "src/logo/main.rs"
